---
- name: "Include OS-specific variables for distribution."
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution|lower == 'freebsd' or ansible_distribution == 'fedora'

- name: "Include version-specific variables for OS."
  include_vars: "{{ specific_variables }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution|lower }}_{{ ansible_distribution_version }}.yml"
        - "vars/{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution|lower }}.yml"
        - "vars/{{ ansible_os_family|lower }}.yml"
      skip: true
      loop_control: loop_var=specific_variables

- name: "Define java packages"
  set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

- name: "Include OS specific tasks"
  include_tasks: "{{ specific_tasks }}"
  when: ansible_os_family == 'RedHat'
  with_first_found:
    - files:
        - "tasks/setup-{{ ansible_distribution|lower }}_{{ ansible_distribution_version }}.yml"
        - "tasks/setup-{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version }}.yml"
        - "tasks/setup-{{ ansible_distribution|lower }}.yml"
        - "tasks/setup-{{ ansible_os_family|lower }}.yml"
      skip: true
      loop_control: loop_var=specific_tasks

- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home
